# SPDX-FileCopyrightText: © 2026 Joe T. Sylve, Ph.D. <joe.sylve@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Integration tests for PSpice decryption.

Test data was generated by Cadence PSpiceEnc (PSpice TI, version string "3")
from a minimal .subckt model file.  Each mode*.lib file was encrypted with
PSpiceEnc -m <N> and the mode4_userkey.lib was encrypted with -m 4 and
CDN_PSPICE_ENCKEYS pointing to a CSV with user key
``0123456789abcdefghijklmnopqrstu``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from spice_crypt import decrypt_stream
from spice_crypt.pspice.decrypt import PSpiceFileParser
from tests.conftest import PLAINTEXT_BODY, extract_body

DATA_DIR = Path(__file__).parent / "data" / "pspice"

USER_KEY = b"0123456789abcdefghijklmnopqrstu"


def _decrypt_file(path: Path, *, user_key: bytes | None = None) -> str:
    """Decrypt a PSpice file and return the full decrypted text."""
    content, _ = decrypt_stream(str(path), user_key=user_key)
    return content


# ---------------------------------------------------------------------------
# Decryption tests for each PSpice encryption mode
# ---------------------------------------------------------------------------


class TestPSpiceDecryption:
    """Verify decryption of PSpiceEnc-generated files across all modes."""

    def test_mode0_des_legacy(self):
        result = _decrypt_file(DATA_DIR / "mode0.lib")
        assert extract_body(result) == PLAINTEXT_BODY

    def test_mode2_des_adv(self):
        result = _decrypt_file(DATA_DIR / "mode2.lib")
        assert extract_body(result) == PLAINTEXT_BODY

    def test_mode3_aes_default(self):
        result = _decrypt_file(DATA_DIR / "mode3.lib")
        assert extract_body(result) == PLAINTEXT_BODY

    def test_mode4_aes_no_user_key(self):
        result = _decrypt_file(DATA_DIR / "mode4.lib")
        assert extract_body(result) == PLAINTEXT_BODY

    def test_mode4_aes_user_key(self):
        result = _decrypt_file(DATA_DIR / "mode4_userkey.lib", user_key=USER_KEY)
        assert extract_body(result) == PLAINTEXT_BODY

    def test_mode4_user_key_wrong_key_fails(self):
        wrong_key = b"wrong_key_padded_to_31_bytes!!!!"
        result = _decrypt_file(DATA_DIR / "mode4_userkey.lib", user_key=wrong_key)
        try:
            body = extract_body(result)
        except StopIteration:
            return  # Garbage output with no .subckt/.ends markers — decryption failed as expected
        assert body != PLAINTEXT_BODY


# ---------------------------------------------------------------------------
# Format auto-detection
# ---------------------------------------------------------------------------


class TestAutoDetection:
    """Verify that decrypt_stream auto-detects PSpice format."""

    @pytest.mark.parametrize("filename", ["mode0.lib", "mode2.lib", "mode3.lib", "mode4.lib"])
    def test_auto_detect(self, filename):
        result = _decrypt_file(DATA_DIR / filename)
        assert "R1 1 2 1k" in result


# ---------------------------------------------------------------------------
# PSpiceFileParser direct usage
# ---------------------------------------------------------------------------


class TestPSpiceFileParser:
    """Test the PSpiceFileParser class directly."""

    def test_parser_stream(self):
        with open(DATA_DIR / "mode3.lib") as f:
            parser = PSpiceFileParser(f)
            chunks = list(parser.decrypt_stream())
        text = b"".join(chunks).decode("utf-8", "replace")
        assert "R1 1 2 1k" in text

    def test_parser_with_user_key(self):
        with open(DATA_DIR / "mode4_userkey.lib") as f:
            parser = PSpiceFileParser(f, user_key_bytes=USER_KEY)
            chunks = list(parser.decrypt_stream())
        text = b"".join(chunks).decode("utf-8", "replace")
        assert "R1 1 2 1k" in text


# ---------------------------------------------------------------------------
# Key recovery (Mode 4 brute-force)
# ---------------------------------------------------------------------------


class TestKeyRecovery:
    """Test Mode 4 AES brute-force key recovery."""

    def test_recover_user_key(self):
        from spice_crypt.pspice import recover_mode4_key

        result = recover_mode4_key(DATA_DIR / "mode4_userkey.lib")

        assert result is not None
        assert result.user_key_full == USER_KEY

    def test_recover_no_user_key_raises(self):
        from spice_crypt.pspice import recover_mode4_key

        # Mode 4 without user key uses default keys; recovery should
        # raise ValueError indicating no brute-force is needed.
        with pytest.raises(ValueError, match="default Mode 4 keys"):
            recover_mode4_key(DATA_DIR / "mode4.lib")


# ---------------------------------------------------------------------------
# Continuation-marker + CRLF handling
# ---------------------------------------------------------------------------


class TestContinuationAndCRLF:
    """Exercise the ``$+`` tail continuation marker and embedded CRLF.

    PSpiceEnc uses two continuation mechanisms:

    1. ``+`` at byte 0 of the next block — SPICE-style continuation of an
       indented next source line.
    2. ``$+`` at bytes 62-63 of the current block — byte-limit mid-content
       split; the next block's payload continues the current one verbatim.

    Source lines can also carry embedded ``\\r`` bytes (from Windows CRLF
    source files).  The fixture here exercises all three behaviours in a
    single synthesised ``.lib``.
    """

    _SENTINEL = b" $jbs$"
    _FILL = b"ADQIRRMGDISLKHOSIMIMCMFREIKFGPCNQQSTKCJGIHLGEMRRNDKG" * 2

    def _padded(self, content: bytes, tail: bytes = b"$\x00") -> bytes:
        """Build a 64-byte padded block: content + ` $jbs$` + fill + tail."""
        remaining = 62 - len(content) - len(self._SENTINEL)
        assert remaining >= 0, f"content too long: {len(content)}"
        return content + self._SENTINEL + self._FILL[:remaining] + tail

    def _full(self, content: bytes) -> bytes:
        """Build a 64-byte full block: 62 bytes content + ``$+`` tail."""
        assert len(content) == 62, f"content must be 62 bytes, got {len(content)}"
        return content + b"$+"

    def _build_lib(self, tmp_path):
        """Synthesise a mode-2 encrypted .lib exercising both continuations."""
        from spice_crypt.pspice.des import PSpiceDES
        from spice_crypt.pspice.keys import derive_keys

        # Logical source (CRLF throughout):
        #   .SUBCKT X_LONG NODE_A NODE_B NODE_C NODE_D NODE_E NODE_F NODE_G\r\n
        #     PARAMS: X=1\r\n                (indented -> SPICE continuation)
        #   R1 1 2 1k\r\n
        #   .ends X_LONG\r\n
        long_line = b".SUBCKT X_LONG NODE_A NODE_B NODE_C NODE_D NODE_E NODE_F NODE_G\r"
        assert len(long_line) == 64  # >62, forces $+ mid-content split

        blocks = [
            self._padded(b"0001.0000 MOCKKEY"),  # header (skipped by decoder)
            self._full(long_line[:62]),  # first 62 bytes + $+ tail
            self._padded(long_line[62:]),  # "G\r" + padding
            self._padded(b"+  PARAMS: X=1\r"),  # + prefix = Style A continuation
            self._padded(b"R1 1 2 1k\r"),  # short CRLF line
            self._padded(b".ends X_LONG\r"),  # end
        ]

        short_key, _ = derive_keys(mode=2, version_str="1")
        cipher = PSpiceDES()
        cipher.set_key(short_key)
        enc_hex = [cipher.process_block(b, decrypt=False).hex().upper() for b in blocks]

        lib_text = "\r\n".join(
            [
                "**$ENCRYPTED_LIB",
                "$CDNENCSTART_ADV1",
                *enc_hex,
                "$CDNENCFINISH",
                "",
            ]
        )
        path = tmp_path / "fixture.lib"
        path.write_text(lib_text)
        return path

    def test_roundtrip_reconstructs_source_lines(self, tmp_path):
        lib = self._build_lib(tmp_path)
        content, _ = decrypt_stream(str(lib))
        # The leading ``+`` is standard SPICE continuation syntax and must
        # be preserved in the decoded output (stripping it would yield
        # unparseable SPICE for downstream simulators).
        expected = (
            ".SUBCKT X_LONG NODE_A NODE_B NODE_C NODE_D NODE_E NODE_F NODE_G\n"
            "+  PARAMS: X=1\n"
            "R1 1 2 1k\n"
            ".ends X_LONG\n"
        )
        assert expected in content
        # Negative assertions: no mid-word cut, no embedded CR.
        assert "NODE_\n" not in content
        assert "\r" not in content

    def test_extract_plaintext_reports_continuation_flag(self):
        from spice_crypt.pspice.decrypt import _extract_plaintext

        # Full block, $+ tail -> continues_next == True
        block_cont = b"A" * 62 + b"$+"
        content, continues = _extract_plaintext(block_cont)
        assert content == b"A" * 62
        assert continues is True

        # Padded block, non-$+ tail -> continues_next == False
        block_end = self._padded(b"hello")
        content, continues = _extract_plaintext(block_end)
        assert content == b"hello"
        assert continues is False

    def test_line_ending_crlf(self, tmp_path):
        """--line-ending crlf (via line_ending=b'\\r\\n') produces CRLF output."""
        lib = self._build_lib(tmp_path)
        out = tmp_path / "out.lib"
        decrypt_stream(str(lib), str(out), line_ending=b"\r\n")
        data = out.read_bytes()
        # Encrypted-body lines (and the preamble) all use CRLF.
        assert b".SUBCKT X_LONG NODE_A NODE_B NODE_C NODE_D NODE_E NODE_F NODE_G\r\n" in data
        assert b"+  PARAMS: X=1\r\n" in data
        # No bare LFs, no bare CRs (every \n is paired, every \r is paired).
        assert data.count(b"\n") == data.count(b"\r\n")
        assert data.count(b"\r") == data.count(b"\r\n")

    def test_line_ending_lf(self, tmp_path):
        """line_ending=b'\\n' normalises any CRLF in input to LF."""
        lib = self._build_lib(tmp_path)
        content, _ = decrypt_stream(str(lib), line_ending=b"\n")
        assert "\r" not in content
        assert ".SUBCKT X_LONG NODE_A NODE_B NODE_C NODE_D NODE_E NODE_F NODE_G\n" in content

    def test_line_ending_preserves_by_default(self, tmp_path):
        """line_ending=None is the documented no-op default."""
        lib = self._build_lib(tmp_path)
        default_content, _ = decrypt_stream(str(lib))
        explicit_content, _ = decrypt_stream(str(lib), line_ending=None)
        assert default_content == explicit_content
